// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate

using System;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.Core.Pipeline;

namespace Playground.ComputeAdhoc
{
    public class AvailabilitySetsClient
    {
        private static readonly string[] AuthScopes = new[] { "https://management.azure.com/.default" };

        // NOTE: skill spec calls for ClientDiagnostics + scope.CreateScope("..."), but
        // ClientDiagnostics is internal to Azure.Core and unusable from an external
        // assembly. Tracking as an open question on the skill.
        private readonly HttpPipeline _pipeline;
        private readonly AvailabilitySetsRestClient _restClient;

        protected AvailabilitySetsClient() { }

        public AvailabilitySetsClient(TokenCredential credential)
            : this(new Uri("https://management.azure.com"), credential, new AvailabilitySetsClientOptions())
        {
        }

        public AvailabilitySetsClient(Uri endpoint, TokenCredential credential, AvailabilitySetsClientOptions options = null)
        {
            if (endpoint == null) throw new ArgumentNullException(nameof(endpoint));
            if (credential == null) throw new ArgumentNullException(nameof(credential));
            options ??= new AvailabilitySetsClientOptions();

            _pipeline = HttpPipelineBuilder.Build(options, new BearerTokenAuthenticationPolicy(credential, AuthScopes));
            _restClient = new AvailabilitySetsRestClient(_pipeline, endpoint, options.Version);
        }

        public virtual Response<AvailabilitySet> CreateOrUpdate(
            string subscriptionId,
            string resourceGroupName,
            string availabilitySetName,
            AvailabilitySet parameters,
            CancellationToken cancellationToken = default)
        {
            using var message = _restClient.CreateCreateOrUpdateRequest(subscriptionId, resourceGroupName, availabilitySetName, parameters);
            _pipeline.Send(message, cancellationToken);
            return ProcessCreateOrUpdateResponse(message);
        }

        public virtual async Task<Response<AvailabilitySet>> CreateOrUpdateAsync(
            string subscriptionId,
            string resourceGroupName,
            string availabilitySetName,
            AvailabilitySet parameters,
            CancellationToken cancellationToken = default)
        {
            using var message = _restClient.CreateCreateOrUpdateRequest(subscriptionId, resourceGroupName, availabilitySetName, parameters);
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            return ProcessCreateOrUpdateResponse(message);
        }

        private Response<AvailabilitySet> ProcessCreateOrUpdateResponse(HttpMessage message)
        {
            var response = message.Response;
            if (response.Status != 200)
            {
                throw new RequestFailedException(response);
            }
            using var doc = JsonDocument.Parse(response.Content.ToMemory());
            var value = AvailabilitySet.Deserialize(doc.RootElement);
            return Response.FromValue(value, response);
        }
    }
}
