// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

using Azure.Core;

namespace Playground.ComputeAdhoc
{
    public class AvailabilitySetsClientOptions : ClientOptions
    {
        public enum ServiceVersion
        {
            V2025_11_01 = 1,
        }

        internal string Version { get; }

        public AvailabilitySetsClientOptions(ServiceVersion version = ServiceVersion.V2025_11_01)
        {
            Version = version switch
            {
                ServiceVersion.V2025_11_01 => "2025-11-01",
                _ => throw new System.ArgumentOutOfRangeException(nameof(version)),
            };
        }
    }
}
