// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class AvailabilitySet : TrackedResource
    {
        public AvailabilitySetProperties Properties { get; set; }
        public Sku Sku { get; set; }

        internal override void WriteProperties(Utf8JsonWriter writer)
        {
            base.WriteProperties(writer);
            if (Properties != null)
            {
                writer.WritePropertyName("properties");
                Properties.Write(writer);
            }
            if (Sku != null)
            {
                writer.WritePropertyName("sku");
                Sku.Write(writer);
            }
        }

        internal static bool TryReadBase(AvailabilitySet model, string name, JsonElement value)
        {
            switch (name)
            {
                case "properties":
                    if (value.ValueKind != JsonValueKind.Null) model.Properties = AvailabilitySetProperties.Deserialize(value);
                    return true;
                case "sku":
                    if (value.ValueKind != JsonValueKind.Null) model.Sku = Sku.Deserialize(value);
                    return true;
            }
            return TrackedResource.TryReadBase(model, name, value);
        }

        internal static new AvailabilitySet Deserialize(JsonElement element)
        {
            var m = new AvailabilitySet();
            foreach (var p in element.EnumerateObject()) TryReadBase(m, p.Name, p.Value);
            return m;
        }
    }
}
