// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate

using System;
using Azure.Core;

namespace Playground.ComputeAdhoc
{
    public class AvailabilitySetsClientOptions : ClientOptions
    {
        internal const ServiceVersion LatestVersion = ServiceVersion.V2025_11_01;

        public enum ServiceVersion
        {
            V2025_11_01 = 1,
        }

        internal string Version { get; }

        public AvailabilitySetsClientOptions(ServiceVersion version = LatestVersion)
        {
            Version = version switch
            {
                ServiceVersion.V2025_11_01 => "2025-11-01",
                _ => throw new ArgumentOutOfRangeException(nameof(version)),
            };
        }
    }
}
