// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate

using System.Collections.Generic;
using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class AvailabilitySetProperties
    {
        public int? PlatformUpdateDomainCount { get; set; }
        public int? PlatformFaultDomainCount { get; set; }
        public IList<WritableSubResource> VirtualMachines { get; set; }
        public WritableSubResource ProximityPlacementGroup { get; set; }
        public IReadOnlyList<InstanceViewStatus> Statuses { get; private set; }
        public ScheduledEventsPolicy ScheduledEventsPolicy { get; set; }
        public VirtualMachineScaleSetMigrationInfo VirtualMachineScaleSetMigrationInfo { get; private set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (PlatformUpdateDomainCount.HasValue) writer.WriteNumber("platformUpdateDomainCount", PlatformUpdateDomainCount.Value);
            if (PlatformFaultDomainCount.HasValue) writer.WriteNumber("platformFaultDomainCount", PlatformFaultDomainCount.Value);
            if (VirtualMachines != null)
            {
                writer.WritePropertyName("virtualMachines");
                writer.WriteStartArray();
                foreach (var v in VirtualMachines) v.Write(writer);
                writer.WriteEndArray();
            }
            if (ProximityPlacementGroup != null) { writer.WritePropertyName("proximityPlacementGroup"); ProximityPlacementGroup.Write(writer); }
            // statuses, virtualMachineScaleSetMigrationInfo are readOnly — omit from body
            if (ScheduledEventsPolicy != null) { writer.WritePropertyName("scheduledEventsPolicy"); ScheduledEventsPolicy.Write(writer); }
            writer.WriteEndObject();
        }

        internal static AvailabilitySetProperties Deserialize(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null) return null;
            var r = new AvailabilitySetProperties();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "platformUpdateDomainCount": r.PlatformUpdateDomainCount = p.Value.GetInt32(); break;
                    case "platformFaultDomainCount": r.PlatformFaultDomainCount = p.Value.GetInt32(); break;
                    case "virtualMachines":
                        var vms = new List<WritableSubResource>();
                        foreach (var item in p.Value.EnumerateArray()) vms.Add(WritableSubResource.Deserialize(item));
                        r.VirtualMachines = vms;
                        break;
                    case "proximityPlacementGroup": r.ProximityPlacementGroup = WritableSubResource.Deserialize(p.Value); break;
                    case "statuses":
                        var sl = new List<InstanceViewStatus>();
                        foreach (var item in p.Value.EnumerateArray()) sl.Add(InstanceViewStatus.Deserialize(item));
                        r.Statuses = sl;
                        break;
                    case "scheduledEventsPolicy": r.ScheduledEventsPolicy = ScheduledEventsPolicy.Deserialize(p.Value); break;
                    case "virtualMachineScaleSetMigrationInfo": r.VirtualMachineScaleSetMigrationInfo = VirtualMachineScaleSetMigrationInfo.Deserialize(p.Value); break;
                }
            }
            return r;
        }
    }
}
