// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

using System.Collections.Generic;
using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class AvailabilitySetProperties
    {
        public int? PlatformUpdateDomainCount { get; set; }
        public int? PlatformFaultDomainCount { get; set; }
        public IList<SubResource> VirtualMachines { get; set; }
        public SubResource ProximityPlacementGroup { get; set; }
        public IList<InstanceViewStatus> Statuses { get; set; }
        public ScheduledEventsPolicy ScheduledEventsPolicy { get; set; }
        public VirtualMachineScaleSetMigrationInfo VirtualMachineScaleSetMigrationInfo { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (PlatformUpdateDomainCount.HasValue) writer.WriteNumber("platformUpdateDomainCount", PlatformUpdateDomainCount.Value);
            if (PlatformFaultDomainCount.HasValue) writer.WriteNumber("platformFaultDomainCount", PlatformFaultDomainCount.Value);
            if (VirtualMachines != null)
            {
                writer.WritePropertyName("virtualMachines");
                writer.WriteStartArray();
                foreach (var item in VirtualMachines) item.Write(writer);
                writer.WriteEndArray();
            }
            if (ProximityPlacementGroup != null)
            {
                writer.WritePropertyName("proximityPlacementGroup");
                ProximityPlacementGroup.Write(writer);
            }
            // statuses is read-only
            if (ScheduledEventsPolicy != null)
            {
                writer.WritePropertyName("scheduledEventsPolicy");
                ScheduledEventsPolicy.Write(writer);
            }
            // virtualMachineScaleSetMigrationInfo is read-only
            writer.WriteEndObject();
        }

        internal static AvailabilitySetProperties Deserialize(JsonElement element)
        {
            var m = new AvailabilitySetProperties();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "platformUpdateDomainCount": m.PlatformUpdateDomainCount = p.Value.GetInt32(); break;
                    case "platformFaultDomainCount": m.PlatformFaultDomainCount = p.Value.GetInt32(); break;
                    case "virtualMachines":
                        {
                            var list = new List<SubResource>();
                            foreach (var item in p.Value.EnumerateArray()) list.Add(SubResource.Deserialize(item));
                            m.VirtualMachines = list;
                            break;
                        }
                    case "proximityPlacementGroup": m.ProximityPlacementGroup = SubResource.Deserialize(p.Value); break;
                    case "statuses":
                        {
                            var list = new List<InstanceViewStatus>();
                            foreach (var item in p.Value.EnumerateArray()) list.Add(InstanceViewStatus.Deserialize(item));
                            m.Statuses = list;
                            break;
                        }
                    case "scheduledEventsPolicy": m.ScheduledEventsPolicy = ScheduledEventsPolicy.Deserialize(p.Value); break;
                    case "virtualMachineScaleSetMigrationInfo": m.VirtualMachineScaleSetMigrationInfo = VirtualMachineScaleSetMigrationInfo.Deserialize(p.Value); break;
                }
            }
            return m;
        }
    }
}
