// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

using System;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.Core.Pipeline;

namespace Playground.ComputeAdhoc
{
    public class AvailabilitySetsClient
    {
        private readonly HttpPipeline _pipeline;
        private readonly AvailabilitySetsClientRestClient _restClient;

        private static readonly Uri DefaultEndpoint = new Uri("https://management.azure.com");
        private static readonly string[] DefaultScopes = new[] { "https://management.azure.com/.default" };

        protected AvailabilitySetsClient()
        {
        }

        public AvailabilitySetsClient(TokenCredential credential)
            : this(DefaultEndpoint, credential, new AvailabilitySetsClientOptions())
        {
        }

        public AvailabilitySetsClient(Uri endpoint, TokenCredential credential)
            : this(endpoint, credential, new AvailabilitySetsClientOptions())
        {
        }

        public AvailabilitySetsClient(Uri endpoint, TokenCredential credential, AvailabilitySetsClientOptions options)
        {
            if (endpoint == null) throw new ArgumentNullException(nameof(endpoint));
            if (credential == null) throw new ArgumentNullException(nameof(credential));
            options ??= new AvailabilitySetsClientOptions();

            _pipeline = HttpPipelineBuilder.Build(options, new HttpPipelinePolicy[] { new BearerTokenAuthenticationPolicy(credential, DefaultScopes) }, Array.Empty<HttpPipelinePolicy>(), new ResponseClassifier());
            _restClient = new AvailabilitySetsClientRestClient(_pipeline, endpoint, options.Version);
        }

        /// <summary>Create or update an availability set.</summary>
        public virtual async Task<Response<AvailabilitySet>> CreateOrUpdateAsync(string subscriptionId, string resourceGroupName, string availabilitySetName, AvailabilitySet parameters, CancellationToken cancellationToken = default)
        {
            if (subscriptionId == null) throw new ArgumentNullException(nameof(subscriptionId));
            if (resourceGroupName == null) throw new ArgumentNullException(nameof(resourceGroupName));
            if (availabilitySetName == null) throw new ArgumentNullException(nameof(availabilitySetName));
            if (parameters == null) throw new ArgumentNullException(nameof(parameters));

            using var message = _restClient.CreateCreateOrUpdateRequest(subscriptionId, resourceGroupName, availabilitySetName, parameters);
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            var response = message.Response;
            switch (response.Status)
            {
                case 200:
                    {
                        using var doc = JsonDocument.Parse(response.ContentStream);
                        var value = AvailabilitySet.Deserialize(doc.RootElement);
                        return Response.FromValue(value, response);
                    }
                default:
                    throw new RequestFailedException(response);
            }
        }

        /// <summary>Create or update an availability set.</summary>
        public virtual Response<AvailabilitySet> CreateOrUpdate(string subscriptionId, string resourceGroupName, string availabilitySetName, AvailabilitySet parameters, CancellationToken cancellationToken = default)
        {
            if (subscriptionId == null) throw new ArgumentNullException(nameof(subscriptionId));
            if (resourceGroupName == null) throw new ArgumentNullException(nameof(resourceGroupName));
            if (availabilitySetName == null) throw new ArgumentNullException(nameof(availabilitySetName));
            if (parameters == null) throw new ArgumentNullException(nameof(parameters));

            using var message = _restClient.CreateCreateOrUpdateRequest(subscriptionId, resourceGroupName, availabilitySetName, parameters);
            _pipeline.Send(message, cancellationToken);
            var response = message.Response;
            switch (response.Status)
            {
                case 200:
                    {
                        using var doc = JsonDocument.Parse(response.ContentStream);
                        var value = AvailabilitySet.Deserialize(doc.RootElement);
                        return Response.FromValue(value, response);
                    }
                default:
                    throw new RequestFailedException(response);
            }
        }
    }
}
