// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate
//
// Maps to: AvailabilitySet (extends TrackedResource).
// NOTE: Skill spec recommends inheriting Azure.ResourceManager.Models.TrackedResourceData,
// but that type's setters are internal and don't round-trip cleanly from raw JSON in
// a hand-written DTO. For this initial run we emit the TrackedResource fields inline.
// (Open question #6 on the skill: provide a recipe for self-contained vs. mapped DTOs.)

using System;
using System.Collections.Generic;
using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class AvailabilitySet
    {
        // Inlined TrackedResource fields
        public string Id { get; private set; }
        public string Name { get; private set; }
        public string Type { get; private set; }
        public string Location { get; set; }
        public IDictionary<string, string> Tags { get; set; }

        // AvailabilitySet-specific
        public AvailabilitySetProperties Properties { get; set; }
        public Sku Sku { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Location != null) writer.WriteString("location", Location);
            if (Tags != null)
            {
                writer.WritePropertyName("tags");
                writer.WriteStartObject();
                foreach (var kv in Tags) writer.WriteString(kv.Key, kv.Value);
                writer.WriteEndObject();
            }
            if (Properties != null) { writer.WritePropertyName("properties"); Properties.Write(writer); }
            if (Sku != null) { writer.WritePropertyName("sku"); Sku.Write(writer); }
            writer.WriteEndObject();
        }

        internal static AvailabilitySet Deserialize(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null) return null;
            var r = new AvailabilitySet();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "id": r.Id = p.Value.GetString(); break;
                    case "name": r.Name = p.Value.GetString(); break;
                    case "type": r.Type = p.Value.GetString(); break;
                    case "location": r.Location = p.Value.GetString(); break;
                    case "tags":
                        var tags = new Dictionary<string, string>();
                        foreach (var t in p.Value.EnumerateObject()) tags[t.Name] = t.Value.GetString();
                        r.Tags = tags;
                        break;
                    case "properties": r.Properties = AvailabilitySetProperties.Deserialize(p.Value); break;
                    case "sku": r.Sku = Sku.Deserialize(p.Value); break;
                }
            }
            return r;
        }
    }
}
