// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class DefaultVirtualMachineScaleSetInfo
    {
        public bool? ConstrainedMaximumCapacity { get; set; }
        public SubResource DefaultVirtualMachineScaleSet { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            // both properties are read-only
            writer.WriteEndObject();
        }

        internal static DefaultVirtualMachineScaleSetInfo Deserialize(JsonElement element)
        {
            var m = new DefaultVirtualMachineScaleSetInfo();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "constrainedMaximumCapacity": m.ConstrainedMaximumCapacity = p.Value.GetBoolean(); break;
                    case "defaultVirtualMachineScaleSet": m.DefaultVirtualMachineScaleSet = SubResource.Deserialize(p.Value); break;
                }
            }
            return m;
        }
    }
}
