// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class DefaultVirtualMachineScaleSetInfo
    {
        public bool? ConstrainedMaximumCapacity { get; set; }
        public WritableSubResource DefaultVirtualMachineScaleSet { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            // both fields are readOnly per swagger; omitted from request body
            writer.WriteEndObject();
        }

        internal static DefaultVirtualMachineScaleSetInfo Deserialize(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null) return null;
            var r = new DefaultVirtualMachineScaleSetInfo();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "constrainedMaximumCapacity": r.ConstrainedMaximumCapacity = p.Value.GetBoolean(); break;
                    case "defaultVirtualMachineScaleSet": r.DefaultVirtualMachineScaleSet = WritableSubResource.Deserialize(p.Value); break;
                }
            }
            return r;
        }
    }
}
