// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class EventGridAndResourceGraph
    {
        public bool? Enable { get; set; }
        public string ScheduledEventsApiVersion { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Enable.HasValue) writer.WriteBoolean("enable", Enable.Value);
            if (ScheduledEventsApiVersion != null) writer.WriteString("scheduledEventsApiVersion", ScheduledEventsApiVersion);
            writer.WriteEndObject();
        }

        internal static EventGridAndResourceGraph Deserialize(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null) return null;
            var r = new EventGridAndResourceGraph();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "enable": r.Enable = p.Value.GetBoolean(); break;
                    case "scheduledEventsApiVersion": r.ScheduledEventsApiVersion = p.Value.GetString(); break;
                }
            }
            return r;
        }
    }
}
