// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

using System;
using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class InstanceViewStatus
    {
        public string Code { get; set; }
        public StatusLevelTypes? Level { get; set; }
        public string DisplayStatus { get; set; }
        public string Message { get; set; }
        public DateTimeOffset? Time { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Code != null) writer.WriteString("code", Code);
            if (Level.HasValue) writer.WriteString("level", Level.Value.ToString());
            if (DisplayStatus != null) writer.WriteString("displayStatus", DisplayStatus);
            if (Message != null) writer.WriteString("message", Message);
            if (Time.HasValue) writer.WriteString("time", Time.Value.ToString("O"));
            writer.WriteEndObject();
        }

        internal static InstanceViewStatus Deserialize(JsonElement element)
        {
            var m = new InstanceViewStatus();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "code": m.Code = p.Value.GetString(); break;
                    case "level":
                        if (Enum.TryParse<StatusLevelTypes>(p.Value.GetString(), out var lvl)) m.Level = lvl;
                        break;
                    case "displayStatus": m.DisplayStatus = p.Value.GetString(); break;
                    case "message": m.Message = p.Value.GetString(); break;
                    case "time": m.Time = p.Value.GetDateTimeOffset(); break;
                }
            }
            return m;
        }
    }
}
