// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate

using System;
using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    /// <summary>Instance view status.</summary>
    public class InstanceViewStatus
    {
        public string Code { get; set; }
        public StatusLevelTypes? Level { get; set; }
        public string DisplayStatus { get; set; }
        public string Message { get; set; }
        public DateTimeOffset? Time { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Code != null) writer.WriteString("code", Code);
            if (Level.HasValue) writer.WriteString("level", Level.Value.ToString());
            if (DisplayStatus != null) writer.WriteString("displayStatus", DisplayStatus);
            if (Message != null) writer.WriteString("message", Message);
            if (Time.HasValue) writer.WriteString("time", Time.Value.ToString("O"));
            writer.WriteEndObject();
        }

        internal static InstanceViewStatus Deserialize(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null) return null;
            var r = new InstanceViewStatus();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "code": r.Code = p.Value.GetString(); break;
                    case "level": r.Level = (StatusLevelTypes)Enum.Parse(typeof(StatusLevelTypes), p.Value.GetString()); break;
                    case "displayStatus": r.DisplayStatus = p.Value.GetString(); break;
                    case "message": r.Message = p.Value.GetString(); break;
                    case "time": r.Time = p.Value.GetDateTimeOffset(); break;
                }
            }
            return r;
        }
    }
}
