// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class Resource
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string ResourceType { get; set; }
        public SystemData SystemData { get; set; }

        internal virtual void WriteProperties(Utf8JsonWriter writer)
        {
            // id, name, type, systemData are read-only - never written
        }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            WriteProperties(writer);
            writer.WriteEndObject();
        }

        internal static bool TryReadBase(Resource model, string name, JsonElement value)
        {
            switch (name)
            {
                case "id": model.Id = value.ValueKind == JsonValueKind.Null ? null : value.GetString(); return true;
                case "name": model.Name = value.ValueKind == JsonValueKind.Null ? null : value.GetString(); return true;
                case "type": model.ResourceType = value.ValueKind == JsonValueKind.Null ? null : value.GetString(); return true;
                case "systemData": model.SystemData = value.ValueKind == JsonValueKind.Null ? null : SystemData.Deserialize(value); return true;
            }
            return false;
        }

        internal static Resource Deserialize(JsonElement element)
        {
            var m = new Resource();
            foreach (var p in element.EnumerateObject()) TryReadBase(m, p.Name, p.Value);
            return m;
        }
    }
}
