// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class ScheduledEventsAdditionalPublishingTargets
    {
        public EventGridAndResourceGraph EventGridAndResourceGraph { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (EventGridAndResourceGraph != null)
            {
                writer.WritePropertyName("eventGridAndResourceGraph");
                EventGridAndResourceGraph.Write(writer);
            }
            writer.WriteEndObject();
        }

        internal static ScheduledEventsAdditionalPublishingTargets Deserialize(JsonElement element)
        {
            var m = new ScheduledEventsAdditionalPublishingTargets();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                if (p.Name == "eventGridAndResourceGraph") m.EventGridAndResourceGraph = EventGridAndResourceGraph.Deserialize(p.Value);
            }
            return m;
        }
    }
}
