// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class ScheduledEventsAdditionalPublishingTargets
    {
        public EventGridAndResourceGraph EventGridAndResourceGraph { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (EventGridAndResourceGraph != null)
            {
                writer.WritePropertyName("eventGridAndResourceGraph");
                EventGridAndResourceGraph.Write(writer);
            }
            writer.WriteEndObject();
        }

        internal static ScheduledEventsAdditionalPublishingTargets Deserialize(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null) return null;
            var r = new ScheduledEventsAdditionalPublishingTargets();
            if (element.TryGetProperty("eventGridAndResourceGraph", out var v))
            {
                r.EventGridAndResourceGraph = Playground.ComputeAdhoc.EventGridAndResourceGraph.Deserialize(v);
            }
            return r;
        }
    }
}
