// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class ScheduledEventsPolicy
    {
        public UserInitiatedRedeploy UserInitiatedRedeploy { get; set; }
        public UserInitiatedReboot UserInitiatedReboot { get; set; }
        public ScheduledEventsAdditionalPublishingTargets ScheduledEventsAdditionalPublishingTargets { get; set; }
        public AllInstancesDown AllInstancesDown { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (UserInitiatedRedeploy != null) { writer.WritePropertyName("userInitiatedRedeploy"); UserInitiatedRedeploy.Write(writer); }
            if (UserInitiatedReboot != null) { writer.WritePropertyName("userInitiatedReboot"); UserInitiatedReboot.Write(writer); }
            if (ScheduledEventsAdditionalPublishingTargets != null) { writer.WritePropertyName("scheduledEventsAdditionalPublishingTargets"); ScheduledEventsAdditionalPublishingTargets.Write(writer); }
            if (AllInstancesDown != null) { writer.WritePropertyName("allInstancesDown"); AllInstancesDown.Write(writer); }
            writer.WriteEndObject();
        }

        internal static ScheduledEventsPolicy Deserialize(JsonElement element)
        {
            var m = new ScheduledEventsPolicy();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "userInitiatedRedeploy": m.UserInitiatedRedeploy = UserInitiatedRedeploy.Deserialize(p.Value); break;
                    case "userInitiatedReboot": m.UserInitiatedReboot = UserInitiatedReboot.Deserialize(p.Value); break;
                    case "scheduledEventsAdditionalPublishingTargets": m.ScheduledEventsAdditionalPublishingTargets = ScheduledEventsAdditionalPublishingTargets.Deserialize(p.Value); break;
                    case "allInstancesDown": m.AllInstancesDown = AllInstancesDown.Deserialize(p.Value); break;
                }
            }
            return m;
        }
    }
}
