// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class ScheduledEventsPolicy
    {
        public UserInitiatedRedeploy UserInitiatedRedeploy { get; set; }
        public UserInitiatedReboot UserInitiatedReboot { get; set; }
        public ScheduledEventsAdditionalPublishingTargets ScheduledEventsAdditionalPublishingTargets { get; set; }
        public AllInstancesDown AllInstancesDown { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (UserInitiatedRedeploy != null) { writer.WritePropertyName("userInitiatedRedeploy"); UserInitiatedRedeploy.Write(writer); }
            if (UserInitiatedReboot != null) { writer.WritePropertyName("userInitiatedReboot"); UserInitiatedReboot.Write(writer); }
            if (ScheduledEventsAdditionalPublishingTargets != null) { writer.WritePropertyName("scheduledEventsAdditionalPublishingTargets"); ScheduledEventsAdditionalPublishingTargets.Write(writer); }
            if (AllInstancesDown != null) { writer.WritePropertyName("allInstancesDown"); AllInstancesDown.Write(writer); }
            writer.WriteEndObject();
        }

        internal static ScheduledEventsPolicy Deserialize(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null) return null;
            var r = new ScheduledEventsPolicy();
            foreach (var p in element.EnumerateObject())
            {
                switch (p.Name)
                {
                    case "userInitiatedRedeploy": r.UserInitiatedRedeploy = UserInitiatedRedeploy.Deserialize(p.Value); break;
                    case "userInitiatedReboot": r.UserInitiatedReboot = UserInitiatedReboot.Deserialize(p.Value); break;
                    case "scheduledEventsAdditionalPublishingTargets": r.ScheduledEventsAdditionalPublishingTargets = ScheduledEventsAdditionalPublishingTargets.Deserialize(p.Value); break;
                    case "allInstancesDown": r.AllInstancesDown = AllInstancesDown.Deserialize(p.Value); break;
                }
            }
            return r;
        }
    }
}
