// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class Sku
    {
        public string Name { get; set; }
        public string Tier { get; set; }
        public long? Capacity { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Name != null) writer.WriteString("name", Name);
            if (Tier != null) writer.WriteString("tier", Tier);
            if (Capacity.HasValue) writer.WriteNumber("capacity", Capacity.Value);
            writer.WriteEndObject();
        }

        internal static Sku Deserialize(JsonElement element)
        {
            var m = new Sku();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "name": m.Name = p.Value.GetString(); break;
                    case "tier": m.Tier = p.Value.GetString(); break;
                    case "capacity": m.Capacity = p.Value.GetInt64(); break;
                }
            }
            return m;
        }
    }
}
