// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    /// <summary>Describes a virtual machine scale set sku.</summary>
    public class Sku
    {
        public string Name { get; set; }
        public string Tier { get; set; }
        public long? Capacity { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Name != null) writer.WriteString("name", Name);
            if (Tier != null) writer.WriteString("tier", Tier);
            if (Capacity.HasValue) writer.WriteNumber("capacity", Capacity.Value);
            writer.WriteEndObject();
        }

        internal static Sku Deserialize(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null) return null;
            var r = new Sku();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "name": r.Name = p.Value.GetString(); break;
                    case "tier": r.Tier = p.Value.GetString(); break;
                    case "capacity": r.Capacity = p.Value.GetInt64(); break;
                }
            }
            return r;
        }
    }
}
