// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate

namespace Playground.ComputeAdhoc
{
    /// <summary>The level code.</summary>
    public enum StatusLevelTypes
    {
        Info,
        Warning,
        Error,
    }
}
