// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

namespace Playground.ComputeAdhoc
{
    public enum StatusLevelTypes
    {
        Info,
        Warning,
        Error
    }
}
