// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: compute/.../common-types/v1/common.json
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class SubResource
    {
        public string Id { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Id != null) writer.WriteString("id", Id);
            writer.WriteEndObject();
        }

        internal static SubResource Deserialize(JsonElement element)
        {
            var m = new SubResource();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "id": m.Id = p.Value.GetString(); break;
                }
            }
            return m;
        }
    }
}
