// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: common-types/resource-management/v3/types.json
// Operations: AvailabilitySets_CreateOrUpdate

using System;
using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class SystemData
    {
        public string CreatedBy { get; set; }
        public string CreatedByType { get; set; }
        public DateTimeOffset? CreatedAt { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedByType { get; set; }
        public DateTimeOffset? LastModifiedAt { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (CreatedBy != null) writer.WriteString("createdBy", CreatedBy);
            if (CreatedByType != null) writer.WriteString("createdByType", CreatedByType);
            if (CreatedAt.HasValue) writer.WriteString("createdAt", CreatedAt.Value.ToString("O"));
            if (LastModifiedBy != null) writer.WriteString("lastModifiedBy", LastModifiedBy);
            if (LastModifiedByType != null) writer.WriteString("lastModifiedByType", LastModifiedByType);
            if (LastModifiedAt.HasValue) writer.WriteString("lastModifiedAt", LastModifiedAt.Value.ToString("O"));
            writer.WriteEndObject();
        }

        internal static SystemData Deserialize(JsonElement element)
        {
            var m = new SystemData();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "createdBy": m.CreatedBy = p.Value.GetString(); break;
                    case "createdByType": m.CreatedByType = p.Value.GetString(); break;
                    case "createdAt": m.CreatedAt = p.Value.GetDateTimeOffset(); break;
                    case "lastModifiedBy": m.LastModifiedBy = p.Value.GetString(); break;
                    case "lastModifiedByType": m.LastModifiedByType = p.Value.GetString(); break;
                    case "lastModifiedAt": m.LastModifiedAt = p.Value.GetDateTimeOffset(); break;
                }
            }
            return m;
        }
    }
}
