// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

using System.Collections.Generic;
using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class TrackedResource : Resource
    {
        public IDictionary<string, string> Tags { get; set; }
        public string Location { get; set; }

        internal override void WriteProperties(Utf8JsonWriter writer)
        {
            base.WriteProperties(writer);
            if (Tags != null)
            {
                writer.WritePropertyName("tags");
                writer.WriteStartObject();
                foreach (var kv in Tags) writer.WriteString(kv.Key, kv.Value);
                writer.WriteEndObject();
            }
            if (Location != null) writer.WriteString("location", Location);
        }

        internal static bool TryReadBase(TrackedResource model, string name, JsonElement value)
        {
            switch (name)
            {
                case "tags":
                    if (value.ValueKind != JsonValueKind.Null)
                    {
                        var d = new Dictionary<string, string>();
                        foreach (var p in value.EnumerateObject())
                            d[p.Name] = p.Value.ValueKind == JsonValueKind.Null ? null : p.Value.GetString();
                        model.Tags = d;
                    }
                    return true;
                case "location": model.Location = value.ValueKind == JsonValueKind.Null ? null : value.GetString(); return true;
            }
            return Resource.TryReadBase(model, name, value);
        }

        internal static new TrackedResource Deserialize(JsonElement element)
        {
            var m = new TrackedResource();
            foreach (var p in element.EnumerateObject()) TryReadBase(m, p.Name, p.Value);
            return m;
        }
    }
}
