// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class UserInitiatedReboot
    {
        public bool? AutomaticallyApprove { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (AutomaticallyApprove.HasValue) writer.WriteBoolean("automaticallyApprove", AutomaticallyApprove.Value);
            writer.WriteEndObject();
        }

        internal static UserInitiatedReboot Deserialize(JsonElement element)
        {
            var m = new UserInitiatedReboot();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                if (p.Name == "automaticallyApprove") m.AutomaticallyApprove = p.Value.GetBoolean();
            }
            return m;
        }
    }
}
