// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class UserInitiatedRedeploy
    {
        public bool? AutomaticallyApprove { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (AutomaticallyApprove.HasValue) writer.WriteBoolean("automaticallyApprove", AutomaticallyApprove.Value);
            writer.WriteEndObject();
        }

        internal static UserInitiatedRedeploy Deserialize(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null) return null;
            var r = new UserInitiatedRedeploy();
            if (element.TryGetProperty("automaticallyApprove", out var v) && v.ValueKind != JsonValueKind.Null)
            {
                r.AutomaticallyApprove = v.GetBoolean();
            }
            return r;
        }
    }
}
