// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class VirtualMachineScaleSetMigrationInfo
    {
        public DefaultVirtualMachineScaleSetInfo DefaultVirtualMachineScaleSetInfo { get; set; }
        public WritableSubResource MigrateToVirtualMachineScaleSet { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            // both fields are readOnly per swagger; omitted from request body
            writer.WriteEndObject();
        }

        internal static VirtualMachineScaleSetMigrationInfo Deserialize(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null) return null;
            var r = new VirtualMachineScaleSetMigrationInfo();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "defaultVirtualMachineScaleSetInfo": r.DefaultVirtualMachineScaleSetInfo = DefaultVirtualMachineScaleSetInfo.Deserialize(p.Value); break;
                    case "migrateToVirtualMachineScaleSet": r.MigrateToVirtualMachineScaleSet = WritableSubResource.Deserialize(p.Value); break;
                }
            }
            return r;
        }
    }
}
