// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ComputeRP.json (2025-11-01)
// Operations: AvailabilitySets_CreateOrUpdate

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class VirtualMachineScaleSetMigrationInfo
    {
        public DefaultVirtualMachineScaleSetInfo DefaultVirtualMachineScaleSetInfo { get; set; }
        public SubResource MigrateToVirtualMachineScaleSet { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            // both properties are read-only
            writer.WriteEndObject();
        }

        internal static VirtualMachineScaleSetMigrationInfo Deserialize(JsonElement element)
        {
            var m = new VirtualMachineScaleSetMigrationInfo();
            foreach (var p in element.EnumerateObject())
            {
                if (p.Value.ValueKind == JsonValueKind.Null) continue;
                switch (p.Name)
                {
                    case "defaultVirtualMachineScaleSetInfo": m.DefaultVirtualMachineScaleSetInfo = DefaultVirtualMachineScaleSetInfo.Deserialize(p.Value); break;
                    case "migrateToVirtualMachineScaleSet": m.MigrateToVirtualMachineScaleSet = SubResource.Deserialize(p.Value); break;
                }
            }
            return m;
        }
    }
}
