// <auto-generated-by-agent />
// Adhoc SDK produced by the generate-adhoc-mgmt-sdk skill.
// Source swagger: ../../azure-rest-api-specs/specification/compute/resource-manager/Microsoft.Compute/Compute/stable/2025-11-01/ComputeRP.json
// Operations: AvailabilitySets_CreateOrUpdate
//
// Maps to: SubResource (common-types/v1/common.json) — kept as a local DTO
// rather than mapped to Azure.Core.WritableSubResource to keep this adhoc
// SDK self-contained.

using System.Text.Json;

namespace Playground.ComputeAdhoc
{
    public class WritableSubResource
    {
        public string Id { get; set; }

        internal void Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Id != null)
            {
                writer.WriteString("id", Id);
            }
            writer.WriteEndObject();
        }

        internal static WritableSubResource Deserialize(JsonElement element)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            var result = new WritableSubResource();
            if (element.TryGetProperty("id", out var id) && id.ValueKind != JsonValueKind.Null)
            {
                result.Id = id.GetString();
            }
            return result;
        }
    }
}
